apiVersion: v1
kind: Service
metadata:
  name: sample-nginx
spec:
  selector:
    app: sample-nginx
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginx
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: sample-nginx
        image: aksclusterjbacr.azurecr.io/sample-nginx:v1
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-nginx
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-nginx
                port:
                  number: 80